spring:
  datasource:
    url: jdbc:postgresql://${WATCHDOG_DB_HOST:localhost}:${WATCHDOG_DB_PORT:5432}/${WATCHDOG_DB_NAME:watchdog_core}
    username: ${WATCHDOG_DB_USERNAME:watchdog}
    password: ${WATCHDOG_DB_PASSWORD:watchdog}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${WATCHDOG_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    org.hibernate.SQL: DEBUG

watchdog:
  kafka:
    enabled: ${WATCHDOG_KAFKA_ENABLED:true}
